datadog:
  apiKeyExistingSecret: datadog-secret
  site: us5.datadoghq.com
  logs:
    enabled: true
    containerCollectAll: true
  ignoreAutoConfig:
    - docker_daemon
  containerExcludeLogs: kube_namespace:datadog.* kube_namespace:kube-.* kube_namespace:calico-.* kube_namespace:tigera-.*
  containerIncludeLogs: kube_namespace:ypp
  kubelet:
    # datadog.kubelet.tlsVerify -- Toggle kubelet TLS verification
    # @default -- true
    tlsVerify:  false

clusterAgent:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

agents:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
