apiVersion: v1
kind: Pod
metadata:
  name: nettools
  namespace: ypp
spec:
  containers:
    - name: nettools
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 128Mi
  restartPolicy: Never