config:
  map: 
    l4: |-
      version: v1
      sharing:
        mps:
          renameByDefault: true
          failRequestsGreaterThanOne: false
          resources:
          - name: nvidia.com/gpu
            replicas: 2
  default: l4
  