apiVersion: apps/v1
kind: Deployment
metadata:
  name: text2img-app
  namespace: ypp
  labels:
    app: text2img
spec:
  replicas: 4
  selector:
    matchLabels:
      app: text2img
  template:
    metadata:
      labels:
        app: text2img
    spec:
      containers:
      - name: text2img
        image: py846260131/kscale-text2img-app:mps-02
        command: [ "python", "main.py", "serve" ]
        ports:
          - containerPort: 8000
            name: serve
        env:
          - name: MODEL_PATH
            value: "/data/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors"
        resources:
          limits:
            cpu: 4
            nvidia.com/gpu.shared: 1
          requests:
            cpu: '500m'
            nvidia.com/gpu.shared: 1
        volumeMounts:
          - name: models-volume
            mountPath: /data
            subPath: data
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ray-service
  namespace: ypp
spec:
  type: NodePort
  selector:
    app: text2img
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30020
      name: serve
