FROM rayproject/ray:2.45.0

RUN pip install --no-cache-dir \
    torch \
    diffusers \
    transformers \
    xformers \
    accelerate \
    smart_open \
    google-cloud-storage \
    boto3 \
    httpx \
    einops==0.8.0 \
    reformer-pytorch==1.4.4 \
    patool==1.12 \
    pywavelets==1.8.0 \
    sktime==0.37.0 \
    tqdm==4.67.1