name: Build Text2Img APP ZIP

on:
  workflow_dispatch: {}

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Zip project
        run: |
          zip -r text2img-app.zip text2img -x '*__pycache__*' 'output'

      - name: Upload to GCS
        run: |
          BUCKET_NAME="kscale-text2img-app"
          OBJECT_NAME="deploy.zip"
          gsutil cp text2img-app.zip gs://$BUCKET_NAME/$OBJECT_NAME